name: flutter_maps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  google_maps_flutter: ^2.6.1
  geolocator: ^11.1.0
  geocoding: ^3.0.0 
  flutter_polyline_points: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assents\images\marker_icon_1.png
